name: Docker CD Pipeline

on:
  workflow_run:
    workflows: [Docker CI Pipeline]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_LOGIN: ${{secrets.DOCKER_LOGIN}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
      - name: rm old container
        run: sudo docker rm -f e-banking-front-github || true


      - name: pull Docker image
        run: sudo docker pull mohammedfahlaoui/e-banking-front-github:latest


      - name: run Docker container
        run: sudo docker run -d -p 80:80 --name e-banking-front-github mohammedfahlaoui/e-banking-front-github:latest






