name: Docker Compose CI

on: [push, pull_request]

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Docker Compose (legacy)
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
        with:
          install-compose: true  # This is the key fix

      - name: Rebuild using compose
        run: |
          docker-compose down
          docker-compose build --no-cache --pull
          docker-compose up -d --force-recreate
          docker-compose ps
