name: Docker CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --output-path=dist/app

      - name: Verify build output
        run: ls -la dist/app

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t e-banking-front .

      - name: Run container
        run: docker run -d -p 80:80 e-banking-front

      - name: Verify deployment
        run: |
          sleep 5 # Wait for container to start
          curl -s http://localhost:80 | grep "e-banking-front"
