name: Docker Compose CI

on: [push, pull_request]

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          # Install Docker Compose v2 (modern plugin version)
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
          docker compose version

      - name: Rebuild using compose
        run: |
          docker compose down
          docker compose build --no-cache --pull
          docker compose up -d --force-recreate
          docker compose ps
