name: Docker Compose CI

on: [push, pull_request]

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          docker compose version  # Note: space instead of hyphen

      - name: Rebuild using compose
        run: |
          docker compose down
          docker compose build --no-cache --pull
          docker compose up -d --force-recreate
          docker compose ps
