name: Docker Compose CI

on: [push, pull_request]

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Rebuild using compose
        run: |
          docker-compose down
          docker-compose build --no-cache --pull
          docker-compose up -d --force-recreate
          docker-compose ps
