name: Docker CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'



      - name: install ng
        run: npm install -g @angular/cli

      - name: npm install
        run: npm install -f

      - name: Build Angular app
        run: npm run build -- --output-path=dist/app

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: docker login -u fahlaouimohammed@gmail.com -p Mohammed20022

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: fahlaouimohammed/e-banking-front-github:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
