name: Docker CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          install-compose: true

      - name: Build and run
        run: |
          docker build -t e-banking-front .
          docker run -d -p 80:80 e-banking-front

      - name: Verify
        run: |
          curl --retry 5 --retry-delay 5 http://localhost:80
