name: Docker CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js v22.12
        uses: actions/setup-node@v3
        with:
          node-version: 22.12




      - name: install ng
        run: npm install -g @angular/cli

      - name: npm install
        run: npm install -f

      - name: Build Angular app
        run: npm run build -- --output-path=dist/e-banking-front

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        env:
          DOCKER_LOGIN: ${{secrets.DOCKER_LOGIN}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: mohammedfahlaoui/e-banking-front-github:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
